# PIPELINE DEFINITION
# Name: pipeline
# Inputs:
#    force: bool [Default: False]
#    input_dir_name: str [Default: 'collections']
#    milvus_collection_name: str [Default: 'chunks']
#    root_mount_path: str [Default: '/tmp']
components:
  comp-add-chunks-to-milvus:
    executorLabel: exec-add-chunks-to-milvus
    inputDefinitions:
      parameters:
        input_dir_name:
          description: Name of the input directory containing chunk directories.
          parameterType: STRING
        milvus_collection_name:
          description: Name of the Milvus collection to add chunks to.
          parameterType: STRING
        root_mount_path:
          description: Root mount path where the input directory is located.
          parameterType: STRING
deploymentSpec:
  executors:
    exec-add-chunks-to-milvus:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add_chunks_to_milvus
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'docling-core==2.31.0'\
          \ 'pymilvus==2.5.8' 'requests==2.32.3' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: quay.io/atarazana/add_chunks_to_milvus:v1.0.5
pipelineInfo:
  name: pipeline
root:
  dag:
    tasks:
      add-chunks-to-milvus:
        cachingOptions: {}
        componentRef:
          name: comp-add-chunks-to-milvus
        inputs:
          parameters:
            input_dir_name:
              componentInputParameter: input_dir_name
            milvus_collection_name:
              componentInputParameter: milvus_collection_name
            root_mount_path:
              componentInputParameter: root_mount_path
        taskInfo:
          name: add-chunks-to-milvus
  inputDefinitions:
    parameters:
      force:
        defaultValue: false
        isOptional: true
        parameterType: BOOLEAN
      input_dir_name:
        defaultValue: collections
        isOptional: true
        parameterType: STRING
      milvus_collection_name:
        defaultValue: chunks
        isOptional: true
        parameterType: STRING
      root_mount_path:
        defaultValue: /tmp
        isOptional: true
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.10.1
