# KFP based Containerfile

ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ARG COMPONENT_NAME

WORKDIR /usr/local/src/kfp/components

COPY ${COMPONENT_NAME}/src/runtime-requirements.txt runtime-requirements.txt

RUN pip install --no-cache-dir -r runtime-requirements.txt
RUN pip install --no-cache-dir kfp==2.8.0

COPY ${COMPONENT_NAME}/src/ .
COPY shared ./shared

