[project]
name = "pipelines"
version = "0.1.0"
description = "Kubeflow pipelines for RAG"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kfp==2.10.1",
    "kfp[kubernetes]==2.10.1",
    "boto3==1.35.54"
]
