ARG BASE_TAG

# Base image for the modelcar Granite image
FROM quay.io/redhat-ai-services/huggingface-modelcar-builder:latest as base

# The model repo to download
ARG MODEL_REPO

# Download the necessary model files
RUN python3 download_model.py --model-repo ${MODEL_REPO}

# Final image containing only the essential model files
FROM registry.access.redhat.com/ubi9/ubi-micro:${BASE_TAG}

# Copy only the necessary model files from the base image
COPY --from=base /models /models

# Set the user to 1001
USER 1001